# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_dates_diag.ui'
#
# Created by: PyQt5 UI code generator 5.12.dev1812231618
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Create_dates_dialog(object):
    def setupUi(self, Create_dates_dialog):
        Create_dates_dialog.setObjectName("Create_dates_dialog")
        Create_dates_dialog.resize(589, 250)
        Create_dates_dialog.setMinimumSize(QtCore.QSize(500, 250))
        Create_dates_dialog.setMaximumSize(QtCore.QSize(1000, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("os_linux_1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Create_dates_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Create_dates_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lab_path = BetterLineEdit(Create_dates_dialog)
        self.lab_path.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lab_path.setStatusTip("")
        self.lab_path.setWhatsThis("")
        self.lab_path.setAccessibleName("")
        self.lab_path.setAccessibleDescription("")
        self.lab_path.setInputMask("")
        self.lab_path.setReadOnly(False)
        self.lab_path.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lab_path.setClearButtonEnabled(False)
        self.lab_path.setObjectName("lab_path")
        self.horizontalLayout_5.addWidget(self.lab_path)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.init_subm_date_time = QtWidgets.QDateTimeEdit(Create_dates_dialog)
        self.init_subm_date_time.setMaximumSize(QtCore.QSize(150, 40))
        self.init_subm_date_time.setCalendarPopup(True)
        self.init_subm_date_time.setObjectName("init_subm_date_time")
        self.horizontalLayout.addWidget(self.init_subm_date_time)
        self.init_label = QtWidgets.QLabel(Create_dates_dialog)
        self.init_label.setObjectName("init_label")
        self.horizontalLayout.addWidget(self.init_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.first_subm_date_time = QtWidgets.QDateTimeEdit(Create_dates_dialog)
        self.first_subm_date_time.setMaximumSize(QtCore.QSize(150, 35))
        self.first_subm_date_time.setCalendarPopup(True)
        self.first_subm_date_time.setObjectName("first_subm_date_time")
        self.horizontalLayout_2.addWidget(self.first_subm_date_time)
        self.first_label = QtWidgets.QLabel(Create_dates_dialog)
        self.first_label.setObjectName("first_label")
        self.horizontalLayout_2.addWidget(self.first_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.second_subm_date_time = QtWidgets.QDateTimeEdit(Create_dates_dialog)
        self.second_subm_date_time.setMaximumSize(QtCore.QSize(150, 35))
        self.second_subm_date_time.setCalendarPopup(True)
        self.second_subm_date_time.setObjectName("second_subm_date_time")
        self.horizontalLayout_3.addWidget(self.second_subm_date_time)
        self.second_label = QtWidgets.QLabel(Create_dates_dialog)
        self.second_label.setObjectName("second_label")
        self.horizontalLayout_3.addWidget(self.second_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.third_subm_date_time = QtWidgets.QDateTimeEdit(Create_dates_dialog)
        self.third_subm_date_time.setMaximumSize(QtCore.QSize(150, 35))
        self.third_subm_date_time.setCalendarPopup(True)
        self.third_subm_date_time.setObjectName("third_subm_date_time")
        self.horizontalLayout_4.addWidget(self.third_subm_date_time)
        self.third_label = QtWidgets.QLabel(Create_dates_dialog)
        self.third_label.setObjectName("third_label")
        self.horizontalLayout_4.addWidget(self.third_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Create_dates_dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Abort|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Create_dates_dialog)
        self.buttonBox.accepted.connect(Create_dates_dialog.accept)
        self.buttonBox.rejected.connect(Create_dates_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Create_dates_dialog)
        Create_dates_dialog.setTabOrder(self.init_subm_date_time, self.first_subm_date_time)
        Create_dates_dialog.setTabOrder(self.first_subm_date_time, self.second_subm_date_time)
        Create_dates_dialog.setTabOrder(self.second_subm_date_time, self.third_subm_date_time)

    def retranslateUi(self, Create_dates_dialog):
        _translate = QtCore.QCoreApplication.translate
        Create_dates_dialog.setWindowTitle(_translate("Create_dates_dialog", "Dialog"))
        self.lab_path.setToolTip(_translate("Create_dates_dialog", "Tripple for file dialog"))
        self.lab_path.setPlaceholderText(_translate("Create_dates_dialog", "DoubleClick to select path"))
        self.init_label.setText(_translate("Create_dates_dialog", "Submission date"))
        self.first_label.setText(_translate("Create_dates_dialog", "1st resubmission"))
        self.second_label.setText(_translate("Create_dates_dialog", "2nd resubmission"))
        self.third_label.setText(_translate("Create_dates_dialog", "3rd resubmission"))

from qt_class_improvements import BetterLineEdit
