# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setEnabled(True)
        Settings.resize(800, 487)
        Settings.setMinimumSize(QtCore.QSize(600, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("os_linux_1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_db = QtWidgets.QGroupBox(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_db.sizePolicy().hasHeightForWidth())
        self.groupBox_db.setSizePolicy(sizePolicy)
        self.groupBox_db.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_db.setAutoFillBackground(False)
        self.groupBox_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_db.setFlat(False)
        self.groupBox_db.setCheckable(False)
        self.groupBox_db.setObjectName("groupBox_db")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_db)
        self.formLayout.setObjectName("formLayout")
        self.label_settings_db = QtWidgets.QLabel(self.groupBox_db)
        self.label_settings_db.setMinimumSize(QtCore.QSize(110, 0))
        self.label_settings_db.setObjectName("label_settings_db")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_settings_db)
        self.input_settings_db = QtWidgets.QLineEdit(self.groupBox_db)
        self.input_settings_db.setEnabled(False)
        self.input_settings_db.setObjectName("input_settings_db")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_settings_db)
        self.label_grades_db = QtWidgets.QLabel(self.groupBox_db)
        self.label_grades_db.setMinimumSize(QtCore.QSize(110, 0))
        self.label_grades_db.setObjectName("label_grades_db")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_grades_db)
        self.input_grades_db = QtWidgets.QLineEdit(self.groupBox_db)
        self.input_grades_db.setText("")
        self.input_grades_db.setObjectName("input_grades_db")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_grades_db)
        self.verticalLayout.addWidget(self.groupBox_db)
        self.groupBox_user = QtWidgets.QGroupBox(Settings)
        self.groupBox_user.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_user.sizePolicy().hasHeightForWidth())
        self.groupBox_user.setSizePolicy(sizePolicy)
        self.groupBox_user.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_user.setObjectName("groupBox_user")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_user)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_logisim_path = QtWidgets.QLabel(self.groupBox_user)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logisim_path.sizePolicy().hasHeightForWidth())
        self.label_logisim_path.setSizePolicy(sizePolicy)
        self.label_logisim_path.setMinimumSize(QtCore.QSize(110, 0))
        self.label_logisim_path.setObjectName("label_logisim_path")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_logisim_path)
        self.input_logisim_path = QtWidgets.QLineEdit(self.groupBox_user)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_logisim_path.sizePolicy().hasHeightForWidth())
        self.input_logisim_path.setSizePolicy(sizePolicy)
        self.input_logisim_path.setText("")
        self.input_logisim_path.setObjectName("input_logisim_path")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_logisim_path)
        self.label_local_stor = QtWidgets.QLabel(self.groupBox_user)
        self.label_local_stor.setMinimumSize(QtCore.QSize(110, 0))
        self.label_local_stor.setObjectName("label_local_stor")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_local_stor)
        self.input_local_stor = QtWidgets.QLineEdit(self.groupBox_user)
        self.input_local_stor.setText("")
        self.input_local_stor.setObjectName("input_local_stor")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_local_stor)
        self.label_rem_stor = QtWidgets.QLabel(self.groupBox_user)
        self.label_rem_stor.setMinimumSize(QtCore.QSize(110, 0))
        self.label_rem_stor.setObjectName("label_rem_stor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_rem_stor)
        self.input_rem_stor = QtWidgets.QLineEdit(self.groupBox_user)
        self.input_rem_stor.setInputMask("")
        self.input_rem_stor.setText("")
        self.input_rem_stor.setObjectName("input_rem_stor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_rem_stor)
        self.verticalLayout.addWidget(self.groupBox_user)
        self.groupBox_local = QtWidgets.QGroupBox(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_local.sizePolicy().hasHeightForWidth())
        self.groupBox_local.setSizePolicy(sizePolicy)
        self.groupBox_local.setMinimumSize(QtCore.QSize(0, 145))
        self.groupBox_local.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_local.setFlat(False)
        self.groupBox_local.setCheckable(False)
        self.groupBox_local.setObjectName("groupBox_local")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_local)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.label_semester = QtWidgets.QLabel(self.groupBox_local)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_semester.sizePolicy().hasHeightForWidth())
        self.label_semester.setSizePolicy(sizePolicy)
        self.label_semester.setMinimumSize(QtCore.QSize(110, 31))
        self.label_semester.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_semester.setObjectName("label_semester")
        self.gridLayout.addWidget(self.label_semester, 0, 3, 1, 1)
        self.label_grad_year = QtWidgets.QLabel(self.groupBox_local)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_grad_year.sizePolicy().hasHeightForWidth())
        self.label_grad_year.setSizePolicy(sizePolicy)
        self.label_grad_year.setMinimumSize(QtCore.QSize(110, 31))
        self.label_grad_year.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_grad_year.setObjectName("label_grad_year")
        self.gridLayout.addWidget(self.label_grad_year, 0, 0, 1, 1)
        self.semester_comboBox = QtWidgets.QComboBox(self.groupBox_local)
        self.semester_comboBox.setEnabled(False)
        self.semester_comboBox.setMinimumSize(QtCore.QSize(110, 31))
        self.semester_comboBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.semester_comboBox.setMaxVisibleItems(3)
        self.semester_comboBox.setMaxCount(5)
        self.semester_comboBox.setObjectName("semester_comboBox")
        self.semester_comboBox.addItem("")
        self.semester_comboBox.addItem("")
        self.semester_comboBox.addItem("")
        self.gridLayout.addWidget(self.semester_comboBox, 0, 4, 1, 1)
        self.spin_year = QtWidgets.QSpinBox(self.groupBox_local)
        self.spin_year.setEnabled(False)
        self.spin_year.setMinimumSize(QtCore.QSize(110, 31))
        self.spin_year.setMaximumSize(QtCore.QSize(110, 16777215))
        self.spin_year.setWrapping(True)
        self.spin_year.setReadOnly(False)
        self.spin_year.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spin_year.setAccelerated(True)
        self.spin_year.setProperty("showGroupSeparator", False)
        self.spin_year.setMinimum(2012)
        self.spin_year.setMaximum(2026)
        self.spin_year.setProperty("value", 2018)
        self.spin_year.setObjectName("spin_year")
        self.gridLayout.addWidget(self.spin_year, 0, 1, 1, 1)
        self.style_checkBox = QtWidgets.QCheckBox(self.groupBox_local)
        self.style_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.style_checkBox.sizePolicy().hasHeightForWidth())
        self.style_checkBox.setSizePolicy(sizePolicy)
        self.style_checkBox.setMinimumSize(QtCore.QSize(0, 31))
        self.style_checkBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.style_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.style_checkBox.setText("")
        self.style_checkBox.setObjectName("style_checkBox")
        self.gridLayout.addWidget(self.style_checkBox, 1, 1, 1, 1)
        self.label_style = QtWidgets.QLabel(self.groupBox_local)
        self.label_style.setMinimumSize(QtCore.QSize(110, 31))
        self.label_style.setObjectName("label_style")
        self.gridLayout.addWidget(self.label_style, 1, 0, 1, 1)
        self.label_grader_name = QtWidgets.QLabel(self.groupBox_local)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_grader_name.sizePolicy().hasHeightForWidth())
        self.label_grader_name.setSizePolicy(sizePolicy)
        self.label_grader_name.setMinimumSize(QtCore.QSize(110, 31))
        self.label_grader_name.setObjectName("label_grader_name")
        self.gridLayout.addWidget(self.label_grader_name, 2, 0, 1, 1)
        self.input_grader_name = QtWidgets.QLineEdit(self.groupBox_local)
        self.input_grader_name.setEnabled(False)
        self.input_grader_name.setMinimumSize(QtCore.QSize(110, 31))
        self.input_grader_name.setMaximumSize(QtCore.QSize(110, 16777215))
        self.input_grader_name.setObjectName("input_grader_name")
        self.gridLayout.addWidget(self.input_grader_name, 2, 1, 1, 1)
        self.label_sync_comm = QtWidgets.QLabel(self.groupBox_local)
        self.label_sync_comm.setObjectName("label_sync_comm")
        self.gridLayout.addWidget(self.label_sync_comm, 2, 3, 1, 1)
        self.sync_command = QtWidgets.QLineEdit(self.groupBox_local)
        self.sync_command.setEnabled(False)
        self.sync_command.setInputMask("")
        self.sync_command.setObjectName("sync_command")
        self.gridLayout.addWidget(self.sync_command, 2, 4, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_local)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.groupBox_db.setTitle(_translate("Settings", "&Database paths:"))
        self.label_settings_db.setText(_translate("Settings", "Settings"))
        self.input_settings_db.setText(_translate("Settings", "./settings.sqlite3"))
        self.label_grades_db.setText(_translate("Settings", "Grades"))
        self.input_grades_db.setPlaceholderText(_translate("Settings", "~/Documents/3130_labs/grades.sqlite3"))
        self.groupBox_user.setTitle(_translate("Settings", "User paths"))
        self.label_logisim_path.setText(_translate("Settings", "Logisim path"))
        self.input_logisim_path.setPlaceholderText(_translate("Settings", "path to logisim executable logisim.jar"))
        self.label_local_stor.setText(_translate("Settings", "Local lab storage"))
        self.input_local_stor.setPlaceholderText(_translate("Settings", "local directory that contains labs, reports, and other working files"))
        self.label_rem_stor.setText(_translate("Settings", "Remote lab storage"))
        self.input_rem_stor.setPlaceholderText(_translate("Settings", "sshfs mounted dir that points to submission directory on the remote server"))
        self.groupBox_local.setTitle(_translate("Settings", "&Local settings"))
        self.label_semester.setText(_translate("Settings", "Grading semester"))
        self.label_grad_year.setText(_translate("Settings", "Grading year"))
        self.semester_comboBox.setItemText(0, _translate("Settings", "Spring"))
        self.semester_comboBox.setItemText(1, _translate("Settings", "Summer"))
        self.semester_comboBox.setItemText(2, _translate("Settings", "Fall"))
        self.label_style.setText(_translate("Settings", "Use styles"))
        self.label_grader_name.setText(_translate("Settings", "Grader name"))
        self.label_sync_comm.setText(_translate("Settings", "Sync command"))
        self.sync_command.setPlaceholderText(_translate("Settings", "rsync -avz ? cp -v ? dd ... ?"))

